// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0WZH_LEG-cDWwon7BKsDucKAYqQ61b0U',
    appId: '1:242468246930:web:7369142951e8207fbd1d4b',
    messagingSenderId: '242468246930',
    projectId: 'kuwait-81c42',
    authDomain: 'kuwait-81c42.firebaseapp.com',
    storageBucket: 'kuwait-81c42.firebasestorage.app',
    measurementId: 'G-HBKZH9VGPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTussNbOsNBpQiR6SMvtGDPglna4g8B7U',
    appId: '1:242468246930:android:499ba2a0e1c01859bd1d4b',
    messagingSenderId: '242468246930',
    projectId: 'kuwait-81c42',
    storageBucket: 'kuwait-81c42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb5hH414XZGmLE651gl41-K5SK6_HswVM',
    appId: '1:242468246930:ios:f49448db6128bc4ebd1d4b',
    messagingSenderId: '242468246930',
    projectId: 'kuwait-81c42',
    storageBucket: 'kuwait-81c42.firebasestorage.app',
    iosBundleId: 'com.kuwaitsouq.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb5hH414XZGmLE651gl41-K5SK6_HswVM',
    appId: '1:242468246930:ios:f49448db6128bc4ebd1d4b',
    messagingSenderId: '242468246930',
    projectId: 'kuwait-81c42',
    storageBucket: 'kuwait-81c42.firebasestorage.app',
    iosBundleId: 'com.kuwaitsouq.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0WZH_LEG-cDWwon7BKsDucKAYqQ61b0U',
    appId: '1:242468246930:web:7f5ecc945f30e153bd1d4b',
    messagingSenderId: '242468246930',
    projectId: 'kuwait-81c42',
    authDomain: 'kuwait-81c42.firebaseapp.com',
    storageBucket: 'kuwait-81c42.firebasestorage.app',
    measurementId: 'G-QRZ9NCTM2G',
  );

}