// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr2_pBthNm1SaBonugXQsiRkOwboUbL_s',
    appId: '1:1019199889747:web:ad8523b2cfe4d0867c01a6',
    messagingSenderId: '1019199889747',
    projectId: 'kuwaitsouq-app',
    authDomain: 'kuwaitsouq-app.firebaseapp.com',
    storageBucket: 'kuwaitsouq-app.firebasestorage.app',
    measurementId: 'G-0GD9B8X2LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCckccxLZlLQOQbAK_rc-UZ3MeAcRWY-7g',
    appId: '1:1019199889747:android:fedddc21ea658d297c01a6',
    messagingSenderId: '1019199889747',
    projectId: 'kuwaitsouq-app',
    storageBucket: 'kuwaitsouq-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfzY3SzPcUgAnPiXkrPxmFtqXo-u8tQs8',
    appId: '1:1019199889747:ios:d29b8326b5eb36db7c01a6',
    messagingSenderId: '1019199889747',
    projectId: 'kuwaitsouq-app',
    storageBucket: 'kuwaitsouq-app.firebasestorage.app',
    androidClientId: '1019199889747-m6du9hqvk59g9cs0kt59e4ou55c2no3c.apps.googleusercontent.com',
    iosClientId: '1019199889747-3ldj67t439gk5lpmjuep70teletqpvb0.apps.googleusercontent.com',
    iosBundleId: 'com.kuwaitsouq.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfzY3SzPcUgAnPiXkrPxmFtqXo-u8tQs8',
    appId: '1:1019199889747:ios:47d467337f86aab97c01a6',
    messagingSenderId: '1019199889747',
    projectId: 'kuwaitsouq-app',
    storageBucket: 'kuwaitsouq-app.firebasestorage.app',
    iosClientId: '1019199889747-jifgmagqe62cgm19uv9hos3vuo6k8mdm.apps.googleusercontent.com',
    iosBundleId: 'com.kuwaitsouq.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr2_pBthNm1SaBonugXQsiRkOwboUbL_s',
    appId: '1:1019199889747:web:bdeb71198400032f7c01a6',
    messagingSenderId: '1019199889747',
    projectId: 'kuwaitsouq-app',
    authDomain: 'kuwaitsouq-app.firebaseapp.com',
    storageBucket: 'kuwaitsouq-app.firebasestorage.app',
    measurementId: 'G-2ZSMWNS9Q5',
  );
}