---
deployment:
  tasks:
    - export DEPLOYPATH=/home/floopkok/kuwaitsouq.online/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R .htaccess $DEPLOYPATH
    - /bin/cp -R .user.ini $DEPLOYPATH
    - /bin/cp -R artisan $DEPLOYPATH
    - /bin/cp -R composer.json $DEPLOYPATH
